/// TOML config file rendering from wizard answers.
use super::helpers::{escape_toml, format_toml_array};
use super::wizard::WizardResult;

/// Render an optional TOML string field: either `key = "value"` or a commented-out placeholder.
fn optional_toml_string(key: &str, value: &Option<String>, placeholder: &str) -> String {
    match value {
        Some(v) => format!("{key} = \"{}\"", escape_toml(v)),
        None => format!("# {key} = \"{placeholder}\""),
    }
}

/// Render an optional TOML array field: either `key = [...]` or a commented-out placeholder.
fn optional_toml_array(key: &str, items: &[String], placeholder: &str) -> String {
    if items.is_empty() {
        format!("# {key} = [\"{placeholder}\"]")
    } else {
        format!("{key} = {}", format_toml_array(items))
    }
}

/// Render a complete, well-commented TOML config from wizard answers.
///
/// Quickstart-aware: empty `industry_topics`, `target_audience`, and
/// `product_description` are rendered as comments so the TOML stays
/// valid while signalling that these fields are optional.
pub(super) fn render_config_toml(r: &WizardResult) -> String {
    let client_secret_line =
        optional_toml_string("client_secret", &r.client_secret, "your-client-secret-here");
    let product_url_line =
        optional_toml_string("product_url", &r.product_url, "https://example.com");

    let product_description_line = if r.product_description.is_empty() {
        "# product_description = \"One-line description of your product\"".to_string()
    } else {
        format!(
            "product_description = \"{}\"",
            escape_toml(&r.product_description)
        )
    };

    let target_audience_line = if r.target_audience.is_empty() {
        "# target_audience = \"Who is your target audience?\"".to_string()
    } else {
        format!("target_audience = \"{}\"", escape_toml(&r.target_audience))
    };

    let industry_topics_line = if r.industry_topics.is_empty() {
        "# industry_topics — defaults to product_keywords".to_string()
    } else {
        format!(
            "industry_topics = {}",
            format_toml_array(&r.industry_topics)
        )
    };

    let brand_voice_line = optional_toml_string(
        "brand_voice",
        &r.brand_voice,
        "Friendly technical expert. Casual, occasionally witty.",
    );
    let reply_style_line = optional_toml_string(
        "reply_style",
        &r.reply_style,
        "Lead with genuine help. Only mention our product if relevant.",
    );
    let content_style_line = optional_toml_string(
        "content_style",
        &r.content_style,
        "Share practical tips with real examples.",
    );
    let persona_opinions_line = optional_toml_array(
        "persona_opinions",
        &r.persona_opinions,
        "Your strong opinion here",
    );
    let persona_experiences_line = optional_toml_array(
        "persona_experiences",
        &r.persona_experiences,
        "Your personal experience here",
    );
    let content_pillars_line = optional_toml_array(
        "content_pillars",
        &r.content_pillars,
        "Your core topic here",
    );

    let targets_section = if r.target_accounts.is_empty() {
        "# --- Target Accounts ---\n\
         # Monitor specific accounts and reply to their conversations.\n\
         # [targets]\n\
         # accounts = [\"elonmusk\", \"levelsio\"]"
            .to_string()
    } else {
        format!(
            "# --- Target Accounts ---\n\
             # Monitor specific accounts and reply to their conversations.\n\
             [targets]\n\
             accounts = {accounts}",
            accounts = format_toml_array(&r.target_accounts),
        )
    };

    let api_key_line = optional_toml_string("api_key", &r.llm_api_key, "your-api-key-here");
    let base_url_line =
        optional_toml_string("base_url", &r.llm_base_url, "http://localhost:11434/v1");

    format!(
        r#"# =============================================================================
# Tuitbot Configuration
# =============================================================================
# Generated by `tuitbot init` setup wizard.
# Edit this file to tune scoring, limits, and intervals.
# Docs: https://github.com/your-org/tuitbot
# =============================================================================

# Queue posts for review before posting (use `tuitbot approve` to review).
approval_mode = {approval_mode}

# --- X API Credentials ---
# Get your credentials from https://developer.x.com/en/portal/dashboard
[x_api]
client_id = "{client_id}"
{client_secret_line}

# --- Authentication Settings ---
[auth]
# Auth mode: "manual" (paste code from browser — works on VPS/headless)
# or "local_callback" (auto-catch via local server — requires a desktop browser).
mode = "manual"
# callback_host = "127.0.0.1"
# callback_port = 8080

# --- Business Profile ---
# Describe your product so Tuitbot can find relevant conversations
# and generate on-brand content.
[business]

# ---- Quickstart (required) ----
product_name = "{product_name}"
product_keywords = {product_keywords}

# ---- Optional context ----
{product_description_line}
{product_url_line}
{target_audience_line}
competitor_keywords = []
{industry_topics_line}

# ---- Enrichment (shape voice and persona) ----
{brand_voice_line}
{reply_style_line}
{content_style_line}
{persona_opinions_line}
{persona_experiences_line}
{content_pillars_line}

# --- Scoring Engine ---
# Controls how tweets are scored for reply-worthiness (0-100 scale).
# Weights should sum to ~100 for balanced scoring.
[scoring]
threshold = 70
keyword_relevance_max = 40.0
follower_count_max = 20.0
recency_max = 15.0
engagement_rate_max = 25.0

# --- Safety Limits ---
# Prevent aggressive posting that could trigger account restrictions.
[limits]
max_replies_per_day = 5
max_tweets_per_day = 6
max_threads_per_week = 1
min_action_delay_seconds = 45
max_action_delay_seconds = 180
max_replies_per_author_per_day = 1
product_mention_ratio = 0.2
banned_phrases = ["check out", "you should try", "I recommend", "link in bio"]

# --- Automation Intervals ---
# How often each loop runs. Shorter intervals use more API quota.
[intervals]
mentions_check_seconds = 300
discovery_search_seconds = 900
content_post_window_seconds = 10800
thread_interval_seconds = 604800

{targets_section}

# --- LLM Provider ---
# Supported: "openai", "anthropic", "ollama"
[llm]
provider = "{llm_provider}"
{api_key_line}
model = "{llm_model}"
{base_url_line}

# --- Data Storage ---
[storage]
db_path = "~/.tuitbot/tuitbot.db"
retention_days = 90

# --- Logging ---
[logging]
# Seconds between periodic status summaries (0 = disabled).
status_interval_seconds = 0

# --- Active Hours Schedule ---
# The bot sleeps outside these hours. Wrapping ranges (e.g. 22-06) are supported.
[schedule]
timezone = "{timezone}"
active_hours_start = {active_hours_start}
active_hours_end = {active_hours_end}
active_days = {active_days}
"#,
        approval_mode = r.approval_mode,
        client_id = escape_toml(&r.client_id),
        client_secret_line = client_secret_line,
        product_name = escape_toml(&r.product_name),
        product_keywords = format_toml_array(&r.product_keywords),
        product_description_line = product_description_line,
        product_url_line = product_url_line,
        target_audience_line = target_audience_line,
        industry_topics_line = industry_topics_line,
        brand_voice_line = brand_voice_line,
        reply_style_line = reply_style_line,
        content_style_line = content_style_line,
        persona_opinions_line = persona_opinions_line,
        persona_experiences_line = persona_experiences_line,
        content_pillars_line = content_pillars_line,
        targets_section = targets_section,
        llm_provider = escape_toml(&r.llm_provider),
        api_key_line = api_key_line,
        llm_model = escape_toml(&r.llm_model),
        base_url_line = base_url_line,
        timezone = escape_toml(&r.timezone),
        active_hours_start = r.active_hours_start,
        active_hours_end = r.active_hours_end,
        active_days = format_toml_array(&r.active_days),
    )
}
